services:
  postgres:
    image: postgres:16-alpine
    container_name: tidn-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: tidn
      POSTGRES_PASSWORD: tidn
      POSTGRES_DB: tidn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tidn']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
